const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const componentDefinitions = [
  { type: 'hero', label: 'Hero', category: 'Sections', description: 'Premium conversion hero with headline, copy and CTA.', schema: { title: { type: 'string' }, eyebrow: { type: 'string' }, body: { type: 'string' }, cta: { type: 'string' } }, defaults: { eyebrow: 'AI-generated launch page', title: 'Maison Lumière', body: 'A luminous luxury storefront generated by Aurelia AI.', cta: 'Shop collection' }, metadata: { supports: ['seo', 'motion', 'gradientMesh'] } },
  { type: 'features', label: 'Features', category: 'Sections', description: 'Three glass feature cards with premium motion metadata.', schema: { title: { type: 'string' }, items: { type: 'array' } }, defaults: { title: 'Everything your customers need', items: [{ title: 'AI layouts', body: 'Industry-smart page structure.' }, { title: 'Luxury motion', body: 'Shimmers, reveals and parallax.' }, { title: 'Commerce ready', body: 'Products, cart and leads.' }] }, metadata: { supports: ['reorder', 'iconPicker'] } },
  { type: 'gallery', label: 'Gallery', category: 'Media', description: 'Editorial parallax image grid.', schema: { title: { type: 'string' }, images: { type: 'asset[]' } }, defaults: { title: 'Editorial gallery', images: [] }, metadata: { supports: ['parallax', 'assetLibrary'], premium: true } },
  { type: 'products', label: 'Product cards', category: 'Commerce', description: 'DB-driven product showcase connected to CMS products.', schema: { title: { type: 'string' }, limit: { type: 'number' } }, defaults: { title: 'Featured products', limit: 3 }, metadata: { supports: ['productSource', 'abTesting', 'modelViewer'] } },
  { type: 'lead', label: 'Lead capture', category: 'Forms', description: 'Contact capture block connected to Lead API.', schema: { title: { type: 'string' }, placeholder: { type: 'string' } }, defaults: { title: 'Join the private list', placeholder: 'email@brand.com' }, metadata: { supports: ['notifications', 'webhooks'] } }
];

const templates = [
  { name: 'Maison Retail', slug: 'maison-retail', industry: 'Luxury retail', description: 'Premium storefront with product cards and soft gold animations.', isPremium: false },
  { name: 'Linear SaaS', slug: 'linear-saas', industry: 'SaaS', description: 'Minimal conversion site with feature blocks and pricing.', isPremium: false },
  { name: 'Atelier Portfolio', slug: 'atelier-portfolio', industry: 'Portfolio', description: 'Scroll storytelling gallery with editorial sections.', isPremium: true },
  { name: '3D Product Drop', slug: '3d-product-drop', industry: 'Commerce', description: '3D model showcase with cart-ready product layout.', isPremium: true }
];

async function main() {
  for (const def of componentDefinitions) {
    await prisma.componentDefinition.upsert({ where: { type: def.type }, update: def, create: def });
  }
  for (const template of templates) {
    const sections = [
      { id: `${template.slug}-hero`, type: 'hero', props: { eyebrow: template.industry, title: template.name, body: template.description, cta: 'Start building' }, animation: { preset: 'luxury-reveal' }, metadata: { source: 'seed' } },
      { id: `${template.slug}-features`, type: 'features', props: componentDefinitions[1].defaults, animation: { preset: 'stagger' }, metadata: { source: 'seed' } },
      { id: `${template.slug}-products`, type: 'products', props: { title: 'Featured collection', limit: 3 }, animation: { preset: 'parallax' }, metadata: { source: 'seed' } }
    ];
    await prisma.template.upsert({
      where: { slug: template.slug },
      update: { ...template, sections, theme: { background: '#F8F6F0', accent: '#D4AF37', text: '#1a1a1a', fonts: { heading: 'Playfair Display', body: 'Inter' } }, metadata: { style: 'premium', seed: true } },
      create: { ...template, sections, theme: { background: '#F8F6F0', accent: '#D4AF37', text: '#1a1a1a', fonts: { heading: 'Playfair Display', body: 'Inter' } }, metadata: { style: 'premium', seed: true } }
    });
  }
  const user = await prisma.user.upsert({ where: { email: process.env.DEV_USER_EMAIL || 'founder@aurelia.ai' }, update: {}, create: { email: process.env.DEV_USER_EMAIL || 'founder@aurelia.ai', name: 'Aurelia Founder' } });
  const website = await prisma.website.upsert({
    where: { slug: 'maison-aurelia' },
    update: {},
    create: { ownerId: user.id, name: 'Maison Aurelia', slug: 'maison-aurelia', industry: 'Luxury retail', theme: { background: '#F8F6F0', accent: '#D4AF37', text: '#1a1a1a' }, metadata: { seed: true }, pages: { create: { title: 'Home', path: '/', sections: [{ id: 'home-hero', type: 'hero', props: { eyebrow: 'Seeded from DB', title: 'Maison Aurelia', body: 'A premium DB-driven storefront.', cta: 'Shop collection' }, animation: { preset: 'luxury-reveal' }, metadata: { source: 'seed' } }, { id: 'home-products', type: 'products', props: { title: 'Featured products', limit: 3 }, animation: {}, metadata: { source: 'seed' } }], seo: { title: 'Maison Aurelia', description: 'Premium storefront.' } } } }
  });
  await prisma.product.upsert({ where: { websiteId_slug: { websiteId: website.id, slug: 'noir-lamp' } }, update: {}, create: { websiteId: website.id, name: 'Noir Lamp', slug: 'noir-lamp', price: 24000, stock: 14, status: 'Active', metadata: { modelViewer: true } } });
  await prisma.product.upsert({ where: { websiteId_slug: { websiteId: website.id, slug: 'champagne-chair' } }, update: {}, create: { websiteId: website.id, name: 'Champagne Chair', slug: 'champagne-chair', price: 89000, stock: 6, status: 'Active', metadata: { modelViewer: true } } });
  await prisma.lead.create({ data: { websiteId: website.id, name: 'Sophia Chen', email: 'sophia@luxe.co', source: 'Homepage form', metadata: { seed: true } } }).catch(() => {});
  await prisma.order.create({ data: { websiteId: website.id, customerName: 'Olivia Hart', total: 31600, status: 'Paid', items: [{ sku: 'NOIR-LAMP', qty: 1 }], metadata: { seed: true } } }).catch(() => {});
}
main().finally(async () => prisma.$disconnect());
