import { LeadCaptureForm } from "@/components/published/LeadCaptureForm";
import { AddToCartButton, StorefrontCart } from "@/components/commerce/StorefrontCart";
import { ModelViewer } from "@/components/published/ModelViewer";
import { ScrollProgress } from "@/components/published/ScrollProgress";
type Section = { id: string; type: string; props: Record<string, any>; animation?: Record<string, any>; metadata?: Record<string, any> };
type Product = { id: string; name: string; price: number; stock: number; metadata?: any };
type Asset = { id: string; url: string; type: string; filename: string };

export function PublishedRenderer({ website, page, products, assets }: { website: any; page: { sections: Section[] }; products: Product[]; assets: Asset[] }) {
  return (
    <main className="min-h-screen bg-[#F8F6F0] text-[#1a1a1a]">
      <ScrollProgress />
      <header className="sticky top-0 z-40 border-b border-black/10 bg-[#F8F6F0]/80 backdrop-blur-2xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4">
          <b className="tracking-tight">{website.name}</b>
          <a href="#contact" className="rounded-full bg-[#1a1a1a] px-5 py-2 text-sm font-bold text-white">Contact</a>
        </div>
      </header>
      {(page.sections || []).map((section) => <PublishedSection key={section.id} slug={website.slug} websiteId={website.id} section={section} products={products} assets={assets} />)}
      <footer className="border-t border-black/10 px-5 py-10 text-center text-sm text-black/50">Published with Aurelia AI</footer>
    <StorefrontCart slug={website.slug} products={products as any} /></main>
  );
}

function PublishedSection({ slug, websiteId, section, products, assets }: { slug: string; websiteId: string; section: Section; products: Product[]; assets: Asset[] }) {
  const p = section.props || {};
  if (section.type === "hero") {
    const heroImage = assets.find((asset) => asset.type.startsWith("image/"));
    return <section className="relative overflow-hidden px-5 py-24"><div className="absolute right-10 top-10 h-72 w-72 rounded-full bg-[#D4AF37]/20 blur-2xl"/><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><span className="rounded-full border border-[#D4AF37]/30 bg-white/60 px-3 py-1 text-xs font-black uppercase tracking-widest text-[#7a5b12]">{p.eyebrow || "Premium"}</span><h1 className="mt-6 font-serif text-6xl font-black leading-[.92] tracking-[-.06em] md:text-8xl">{p.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-black/60">{p.body}</p><a href="#products" className="mt-8 inline-flex rounded-full bg-gradient-to-br from-[#D4AF37] to-[#92701c] px-6 py-3 font-bold text-white shadow-2xl">{p.cta || "Explore"}</a></div><div className="overflow-hidden rounded-[2rem] border border-black/10 bg-white/60 p-4 shadow-2xl">{heroImage ? <img src={heroImage.url} alt={heroImage.filename} className="h-[420px] w-full rounded-[1.5rem] object-cover"/> : <div className="h-[420px] rounded-[1.5rem] bg-gradient-to-br from-white via-[#eadfc9] to-[#D4AF37]"/>}</div></div></section>;
  }
  if (section.type === "features") return <section className="px-5 py-20"><div className="mx-auto max-w-7xl"><h2 className="font-serif text-5xl font-black tracking-[-.05em]">{p.title}</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{(p.items || []).map((item: any, i: number) => <div key={i} className="rounded-[2rem] border border-black/10 bg-white/60 p-7 shadow-xl backdrop-blur-xl"><b>{item.title}</b><p className="mt-3 leading-7 text-black/55">{item.body}</p></div>)}</div></div></section>;

  if (section.type === "scrollStory") return <section className="bg-[#1a1a1a] px-5 py-24 text-white"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.88fr_1.12fr]"><div className="lg:sticky lg:top-24 lg:h-fit"><span className="rounded-full border border-[#D4AF37]/30 bg-white/10 px-3 py-1 text-xs font-black uppercase tracking-widest text-[#f2d77d]">{p.eyebrow || "Story"}</span><h2 className="mt-6 font-serif text-6xl font-black leading-[.95] tracking-[-.06em]">{p.title || "A journey told in motion"}</h2><p className="mt-5 leading-8 text-white/60">{p.body || "A cinematic section for product launches, case studies and editorial brand stories."}</p></div><div className="grid gap-8"><div className="sticky top-24 overflow-hidden rounded-[2.5rem] border border-white/10 bg-white/10 shadow-2xl">{p.mediaUrl ? (p.mediaType === "video" || String(p.mediaUrl).match(/\.(mp4|webm)(\?|$)/i) ? <video src={p.mediaUrl} className="h-[520px] w-full object-cover" muted autoPlay loop playsInline controls /> : <img src={p.mediaUrl} alt={p.title || "Story visual"} className="h-[520px] w-full object-cover" />) : <div className="grid h-[520px] place-items-center bg-gradient-to-br from-[#D4AF37]/30 to-white/10"><span className="text-8xl">◌</span></div>}</div><div className="grid gap-4">{(p.chapters || []).map((chapter: any, i: number) => <article key={i} className="rounded-[2rem] border border-white/10 bg-white/10 p-7 backdrop-blur"><span className="text-sm font-black text-[#f2d77d]">0{i + 1}</span><h3 className="mt-3 text-2xl font-black">{chapter.title}</h3><p className="mt-3 leading-7 text-white/60">{chapter.body}</p></article>)}</div></div></div></section>;
  if (section.type === "gallery") return <section className="px-5 py-20"><div className="mx-auto max-w-7xl"><h2 className="font-serif text-5xl font-black tracking-[-.05em]">{p.title}</h2><div className="mt-8 grid gap-4 md:grid-cols-[1.4fr_1fr_1fr]">{[0,1,2].map((i) => (p.images || [])[i] ? <img key={i} src={(p.images || [])[i]} alt={p.title || "Gallery"} className="h-72 rounded-[2rem] object-cover shadow-xl" /> : <div key={i} className="h-72 rounded-[2rem] bg-gradient-to-br from-white via-[#eadfc9] to-[#D4AF37] shadow-xl" />)}</div></div></section>;
  if (section.type === "products") return <section id="products" className="px-5 py-20"><div className="mx-auto max-w-7xl"><h2 className="font-serif text-5xl font-black tracking-[-.05em]">{p.title}</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{products.slice(0, p.limit || 3).map((product) => <article key={product.id} className="rounded-[2rem] border border-black/10 bg-white/70 p-5 shadow-xl">{(product as any).metadata?.imageUrl ? <img src={(product as any).metadata.imageUrl} alt={product.name} className="mb-5 h-44 w-full rounded-[1.5rem] object-cover"/> : <div className="mb-5 h-44 rounded-[1.5rem] bg-gradient-to-br from-[#1a1a1a] to-[#D4AF37]"/>}<b>{product.name}</b><p className="mt-2 text-black/55">${(product.price / 100).toFixed(2)}</p><AddToCartButton productId={product.id} /></article>)}</div></div></section>;
  if (section.type === "model3d") return <section className="px-5 py-24"><div className="mx-auto grid max-w-7xl gap-10 rounded-[2.5rem] border border-black/10 bg-white/60 p-8 shadow-2xl backdrop-blur-xl md:grid-cols-2 md:items-center"><div><span className="rounded-full border border-[#D4AF37]/30 bg-white/60 px-3 py-1 text-xs font-black uppercase tracking-widest text-[#7a5b12]">3D detail</span><h2 className="mt-5 font-serif text-5xl font-black tracking-[-.05em]">{p.title || "Explore every detail"}</h2><p className="mt-5 leading-8 text-black/60">{p.body || "A closer look at the craftsmanship, materials and form."}</p></div><ModelViewer url={p.assetUrl} scale={p.scale} autoRotate={p.autoRotate} environment={p.environment} /></div></section>;
  if (section.type === "lead") return <section id="contact" className="px-5 py-20"><div className="mx-auto max-w-5xl rounded-[2rem] bg-[#1a1a1a] p-10 text-white"><h2 className="font-serif text-5xl font-black tracking-[-.05em]">{p.title}</h2><LeadCaptureForm websiteId={websiteId} placeholder={p.placeholder || "email@brand.com"} /></div></section>;
  return <PremiumSectionFallback section={section} />;
}

function PremiumSectionFallback({ section }: { section: Section }) {
  const p = section.props || {};
  const title = p.title || p.headline || p.eyebrow || section.type;
  const items = p.cards || p.items || p.steps || p.plans || p.members || p.panels || p.features || [];
  return <section className="px-5 py-24"><div className="mx-auto max-w-7xl rounded-[2.5rem] border border-white/10 bg-white/[.06] p-8 shadow-2xl backdrop-blur-xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><span className="rounded-full border border-violet/40 bg-violet/15 px-3 py-1 text-xs font-black uppercase tracking-widest text-violet-200">{section.type}</span><h2 className="mt-5 max-w-3xl text-5xl font-black leading-[.95] tracking-[-.06em] text-white">{title}</h2>{p.body && <p className="mt-4 max-w-2xl text-lg leading-8 text-white/55">{p.body}</p>}</div></div><div className="grid gap-4 md:grid-cols-3">{(Array.isArray(items) && items.length ? items : [{ title: p.title || section.type, body: p.description || "Premium metadata-driven section ready for a dedicated renderer." }]).slice(0, 6).map((item: any, i: number) => <article key={item.id || i} className="rounded-[2rem] border border-white/10 bg-black/20 p-6"><span className="text-sm font-black text-cyan">{String(i + 1).padStart(2, "0")}</span><h3 className="mt-3 text-xl font-black text-white">{item.title || item.name || item.label || item.value || "Premium block"}</h3><p className="mt-3 leading-7 text-white/50">{item.body || item.description || item.quote || item.answer || item.role || "Configured from template JSON."}</p></article>)}</div></div></section>;
}
