import { z } from "zod";

export const sectionTypes = ["hero", "features", "gallery", "products", "lead", "model3d"] as const;
export const sectionTypeSchema = z.enum(sectionTypes);

export const sectionSchema = z.object({
  id: z.string(),
  type: sectionTypeSchema,
  props: z.record(z.any()).default({}),
  animation: z.record(z.any()).default({}),
  metadata: z.record(z.any()).default({})
});

export const pageSectionsSchema = z.array(sectionSchema);

export const componentDefinitions = [
  {
    type: "hero",
    label: "Hero",
    category: "Sections",
    description: "Premium conversion hero with headline, copy and CTA.",
    schema: {
      title: { type: "string", label: "Headline", required: true },
      eyebrow: { type: "string", label: "Eyebrow" },
      body: { type: "string", label: "Body" },
      cta: { type: "string", label: "CTA" }
    },
    defaults: {
      eyebrow: "AI-generated launch page",
      title: "Maison Lumière",
      body: "A luminous luxury storefront generated by Aurelia AI.",
      cta: "Shop collection"
    },
    metadata: { supports: ["seo", "motion", "gradientMesh"], premium: false }
  },
  {
    type: "features",
    label: "Features",
    category: "Sections",
    description: "Three glass feature cards with premium motion metadata.",
    schema: {
      title: { type: "string", label: "Title" },
      items: { type: "array", label: "Feature cards" }
    },
    defaults: {
      title: "Everything your customers need",
      items: [
        { title: "AI layouts", body: "Industry-smart page structure." },
        { title: "Luxury motion", body: "Shimmers, reveals and parallax." },
        { title: "Commerce ready", body: "Products, cart and leads." }
      ]
    },
    metadata: { supports: ["reorder", "iconPicker"], premium: false }
  },
  {
    type: "gallery",
    label: "Gallery",
    category: "Media",
    description: "Editorial parallax image grid.",
    schema: { title: { type: "string", label: "Title" }, images: { type: "asset[]", label: "Images" } },
    defaults: { title: "Editorial gallery", images: [] },
    metadata: { supports: ["parallax", "assetLibrary"], premium: true }
  },
  {
    type: "products",
    label: "Product cards",
    category: "Commerce",
    description: "DB-driven product showcase connected to CMS products.",
    schema: { title: { type: "string", label: "Title" }, limit: { type: "number", label: "Limit" } },
    defaults: { title: "Featured products", limit: 3 },
    metadata: { supports: ["productSource", "abTesting", "modelViewer"], premium: false }
  },

  {
    type: "model3d",
    label: "3D Model Showcase",
    category: "Commerce",
    description: "Premium GLB/GLTF product model section backed by Vercel Blob assets.",
    schema: {
      title: { type: "string", label: "Title" },
      body: { type: "string", label: "Body" },
      assetUrl: { type: "asset", label: "3D model URL" }
    },
    defaults: { title: "Explore every detail", body: "A closer look at the craftsmanship, materials and form.", assetUrl: "" },
    metadata: { supports: ["modelViewer", "lighting", "commerce"], premium: true }
  },
  {
    type: "lead",
    label: "Lead capture",
    category: "Forms",
    description: "Contact capture block connected to Lead API.",
    schema: { title: { type: "string", label: "Title" }, placeholder: { type: "string", label: "Placeholder" } },
    defaults: { title: "Join the private list", placeholder: "email@brand.com" },
    metadata: { supports: ["notifications", "webhooks"], premium: false }
  }
] as const;

export function createSection(type: string) {
  const definition = componentDefinitions.find((item) => item.type === type);
  if (!definition) throw new Error(`Unknown component type: ${type}`);
  return {
    id: crypto.randomUUID(),
    type: definition.type,
    props: definition.defaults,
    animation: { preset: "luxury-reveal", duration: 0.8 },
    metadata: { source: "component-library", definitionVersion: 1 }
  };
}
