import type { Lead, Order, Product, SiteSection, Website } from "@/lib/types";

export const defaultSections: SiteSection[] = [
  { id: "s1", type: "hero", title: "Maison Lumière", body: "A luminous luxury storefront generated by Aurelia AI." },
  { id: "s2", type: "features", title: "Everything your customers need", body: "Glass cards, gold motion, parallax-ready layouts and conversion-first copy." },
  { id: "s3", type: "products", title: "Featured collection", body: "Sell premium products with an elegant shopping experience." }
];

export const websites: Website[] = [
  { id: "w1", name: "Maison Lumière", slug: "maison-lumiere", status: "Draft", sections: defaultSections, updatedAt: "Today" },
  { id: "w2", name: "Atelier Preview", slug: "atelier-preview", status: "Draft", sections: defaultSections.slice(0, 2), updatedAt: "Yesterday" },
  { id: "w3", name: "Serum Launch", slug: "serum-launch", status: "Published", sections: defaultSections, updatedAt: "Jun 20" }
];

export const products: Product[] = [
  { id: "p1", name: "Noir Lamp", price: 240, stock: 14, status: "Active" },
  { id: "p2", name: "Champagne Chair", price: 890, stock: 6, status: "Active" },
  { id: "p3", name: "Silk Serum", price: 76, stock: 33, status: "Draft" }
];

export const leads: Lead[] = [
  { id: "l1", name: "Sophia Chen", email: "sophia@luxe.co", source: "Homepage form", createdAt: "Today" },
  { id: "l2", name: "Milan Reed", email: "milan@studio.io", source: "Product page", createdAt: "Yesterday" }
];

export const orders: Order[] = [
  { id: "#1007", customer: "Olivia Hart", total: 316, status: "Paid" },
  { id: "#1008", customer: "Milan Reed", total: 890, status: "Packing" },
  { id: "#1009", customer: "Nora Vale", total: 76, status: "Shipped" }
];

export const templates = [
  { name: "Maison Retail", type: "Luxury retail", description: "Premium storefront with product cards and soft gold animations." },
  { name: "Linear SaaS", type: "SaaS", description: "Minimal conversion site with feature blocks and pricing." },
  { name: "Atelier Portfolio", type: "Portfolio", description: "Scroll storytelling gallery with editorial sections." },
  { name: "Wellness Launch", type: "Wellness", description: "Lead capture, packages and calming visual rhythm." },
  { name: "Interior Studio", type: "Interior", description: "Parallax showroom for high-end design studios." },
  { name: "3D Product Drop", type: "Commerce", description: "3D model showcase with cart-ready product layout." }
];
