import { Badge, Card } from "@/components/ui/Card";

function MiniTable({ title, rows }: { title: string; rows: React.ReactNode[] }) {
  return <Card className="p-6"><h2 className="text-xl font-black">{title}</h2><div className="mt-4 grid gap-3">{rows.length ? rows : <p className="text-sm text-charcoal/50">No records yet.</p>}</div></Card>;
}

export function AdminDashboard({ data }: { data: any }) {
  const stats = [
    ["Users", data.users], ["Websites", data.websites], ["Domains", data.domains],
    ["Subscriptions", data.subscriptions], ["Orders", data.orders], ["Leads", data.leads], ["Webhook events", data.webhooks]
  ];
  return <div className="mx-auto max-w-7xl px-4 py-8"><div className="mb-8"><p className="text-xs font-black uppercase tracking-[.22em] text-[#8a6818]">Platform admin</p><h1 className="mt-3 font-serif text-6xl font-black tracking-[-.06em]">Operations overview</h1><p className="mt-4 text-charcoal/60">Monitor platform health, users, domains, subscriptions and system events.</p></div><div className="grid gap-4 md:grid-cols-4">{stats.map(([label, value]) => <Card key={label} className="p-6"><p className="text-sm font-bold text-charcoal/50">{label}</p><b className="mt-2 block text-4xl tracking-[-.05em]">{value}</b></Card>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-2"><MiniTable title="Recent users" rows={data.recentUsers.map((u: any) => <div key={u.id} className="rounded-2xl bg-white/70 p-4"><b>{u.name || u.email}</b><p className="text-xs text-charcoal/45">{u.email}</p></div>)} /><MiniTable title="Recent websites" rows={data.recentWebsites.map((w: any) => <div key={w.id} className="rounded-2xl bg-white/70 p-4"><div className="flex justify-between"><b>{w.name}</b><Badge>{w.status}</Badge></div><p className="text-xs text-charcoal/45">{w.owner?.email} · {w.domains?.length || 0} domains</p></div>)} /><MiniTable title="Recent subscriptions" rows={data.recentSubscriptions.map((s: any) => <div key={s.id} className="rounded-2xl bg-white/70 p-4"><div className="flex justify-between"><b>{s.user?.email}</b><Badge>{s.plan}</Badge></div><p className="text-xs text-charcoal/45">{s.status}</p></div>)} /><MiniTable title="Recent domains" rows={data.recentDomains.map((d: any) => <div key={d.id} className="rounded-2xl bg-white/70 p-4"><div className="flex justify-between"><b>{d.hostname}</b><Badge>{d.status}</Badge></div><p className="text-xs text-charcoal/45">{d.website?.name}</p></div>)} /><MiniTable title="Recent audit logs" rows={data.auditLogs.map((log: any) => <div key={log.id} className="rounded-2xl bg-white/70 p-4"><div className="flex justify-between gap-3"><Badge>{log.action}</Badge><span className="text-xs text-charcoal/45">{new Date(log.createdAt).toLocaleString()}</span></div><p className="mt-2 text-sm text-charcoal/60">{log.resource} {log.resourceId || ""}</p><p className="mt-1 text-xs text-charcoal/45">{log.user?.email || "System"}</p></div>)} /><MiniTable title="Webhook events" rows={data.webhookEvents.map((event: any) => <div key={event.id} className="rounded-2xl bg-white/70 p-4"><div className="flex justify-between gap-3"><Badge>{event.type}</Badge><span className="text-xs text-charcoal/45">{event.processed ? "Processed" : "Pending"}</span></div><p className="mt-2 break-all text-xs text-charcoal/50">{event.id}</p></div>)} /></div></div>;
}
